### ISSUE TITLE
Suggestion: Build a container image of the tool 

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/release-manager#104]
## Suggestion

I propose/suggest that we build a container image of the "issue-manager" to avoid that a lambda user must git clone the project locally and build it to use it. The image could be build automatically using a github action and next pushed on quay.io snowdrop

WDYT ? @jacobdotcosta @metacosm @gytis

**Comment by metacosm** [comment]
Which lambda user? Presumably everyone who will use that tool knows how to build and run a java application… and I'd rather avoid unnecessary work and CO2 emissions if there's no clear utility to generating an image.

**Comment by cmoulliard** [comment]
> and I'd rather avoid unnecessary work and CO2 emissions

x individual downloads followed by x `mvn package` cost certainly more than using a container build image ...

**Comment by metacosm** [comment]
> > and I'd rather avoid unnecessary work and CO2 emissions
> 
> x individual downloads followed by x `mvn package` cost certainly more than using a container build image ...

Not when the image is automatically generated on each push by CI…

**Comment by cmoulliard** [comment]
Added a github workflow action for that purpose
