### ISSUE TITLE
New command to initialize a new major-minor version

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/release-manager#113]
This command (e.g. `new-maj-min`) should:

- [x]  create the `sb-<major>.<minor>.x` branch on the spring-boot-bom project, by cloning the branch corresponding to the previous version.
- [x] delete all the `release-*.yml` files from the new `spring-boot-bom` repository branch.
- [x] Create the `springboot/<major>.<minor>` folder on BuildConfigurations project copying the `build-config.yaml` from the previous version.

**Comment by metacosm** [comment]
Again, why couldn't this be done by the `start-release` command?

**Comment by jacobdotcosta** [comment]
Because this is launched before the `align bom with upstream` which ATM is a atomist action.

**Comment by metacosm** [comment]
Imo, there should only be one command that deals with releases and is smart enough to figure out what it needs to do based on the parameters you provide.

**Comment by jacobdotcosta** [comment]
I agree, but I think we should leave this to a 2nd phase after having each of the commands implemented.
