### ISSUE TITLE
Rename issues-manager github repo to release(s)-manager

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/release-manager#115]

**Comment by jacobdotcosta** [comment]
DONE

**Comment by metacosm** [comment]
Nope, there are still lots of references to `issues-manager` in the code and these should be renamed as well, making sure that they don't affect existing automation first.

**Comment by cmoulliard** [comment]
Can you check again @jacobdotcosta ?

**Comment by aureamunoz** [comment]
It's done.
