### ISSUE TITLE
Update the build-config file with the info provided in JIRA

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/release-manager#98]
Implement a new process that gathers information for each of the JIRA components and updates the build configuration with the values provided.

## Input:
- spring boot version (e.g. `2.4.3`)
- OPTIONAL switch to override overwriting components already updated
   - The default behavior is not to update components already updated. If this option/switch is set (no value needs to be associated) the process should override this behavior and force the update of all components.

## Pre-Validations:
1. The version provided as INPUT is the same as the one in the `pom.xml` as well as the `release.yml` file in the corresponding `spring-boot-bom` `sb-<major>.<minor>.x` branch.

## Process:
1. Collect the version from the release file as well as from the pom.xml file
1. Identify the gitlab branch/MR which is being used
   1. Clone the repository
   2. Create a branch - the branch name must follow a predefined rule such as `issues-manager-<major>.<minor>.<fix>`
   3. If no branch/MR exists, or it's closed, create a new branch
1. Collect each of the issues from the release file.
1. Parse the corresponding JIRA description
   1. If the component description is the default one, skip it
   1. In there are parsing errors add a comment to the JIRA informing of the problem
   1. The process shouldn't stop in case errors are found on one component
1. Update the `build-config` file for the `<major>.<minor>` version
   - Any version information should be stored in variables defined at the beginning of the `build-config` file
1. Create an MR for the `build-configurations` project with the changes
   - if no changes are made the process should detect that and not push anything 
1. Marks the component(s) as updated in the release file
   - if no changes are made the process should detect that and not push anything 

## Output:
- Text resume of the process:
   - Which components were changed
   - Which components failed
   - Gitlab MR for the `build-configurations` repository with the changes made
   - github commit on the `sb-<major>.<minor>.x` branch of the `spring-boot-bom` repository with the changes to the release file

## Fails if:
   - The Spring Boot version in the `pom.xml` file is mismatch
   - There is no release file
   - The `build-config` file for the `<major>.<minor>` version doesn't exist

## Info to parse
This is an example using the dekorate GAV.

The release file has something like this:

```
- name: Dekorate
  jira:
    project: ENTSBT
    key: ENTSBT-968
    assignee: xxx
  properties:
  - dekorate
```

From JIRA the information is currently under the following format:
```
io.dekorate:dekorate-spring-bom (upstream version is 1.0.3):
product name: [ replace by associated product name e.g. JWS ]
product version: [ replace by associated project version e.g. 5.3.1 ]
supported version: [ replace by appropriate -redhat version ]
end of support: [ replace by end of support date in yyyy-mm-dd format ]
```

This section should be filled with something like this...
```
io.dekorate:dekorate-spring-bom (upstream version is 1.0.3):
product name: dekorate
product version: 0.0.0
supported version: 0.0.0-redhat
end of support: [ replace by end of support date in yyyy-mm-dd format ]
```
In this case the `build-configurations` yaml file should update the following property:
```
#!dekorateVersion=0.0.0
```
> NOTE: Probably the `build-configurations` variable names might be adapted to this process.

**Comment by metacosm** [comment]
I'd specify the fail conditions a little bit more: the tool should make all the changes it can and inform users if the JIRA somehow doesn't conform to the expected format or cannot be parsed. More precisely, an error in a given JIRA shouldn't fail the whole process, the tool should go through the MR creation and accumulate then report all encountered issues. 

Moreover the process should be incremental: running it several times should only modify the existing MR, not create a new one for a given release. This means that the process should modify the release descriptor with the created MR information in case it needs to be run again for the same release.

**Comment by cmoulliard** [comment]
> * override of the components already updated

Can you clarify this point and perhaps provide an example to make this text more readable ?

**Comment by cmoulliard** [comment]
> 1. The version provided

Are you talking about the Spring Boot version, the version of a component (e.g infinispan, tomcat, ...) ?

**Comment by cmoulliard** [comment]
General remark: Using some concrete examples should help to figure out the use case you describe @jacobdotcosta

**Comment by metacosm** [comment]
> > 1. The version provided
> 
> Are you talking about the Spring Boot version, the version of a component (e.g infinispan, tomcat, ...) ?

This is about the release version i.e. the Spring Boot version (possibly simplified, i.e. without `.RELEASE`).

**Comment by yharish991** [comment]
will `build-configurations` be a new repository?I couldn't find it in gitlab and github

**Comment by jacobdotcosta** [comment]
> > 1. The version provided
> 
> Are you talking about the Spring Boot version, the version of a component (e.g infinispan, tomcat, ...) ?

Yes, I've clarified the comment.

**Comment by jacobdotcosta** [comment]
> will `build-configurations` be a new repository?I couldn't find it in gitlab and github

It's a gitlab repository, I'll send it to you.

**Comment by cmoulliard** [comment]
> * If this option is set

How such an option is set ? Is it a boolean, a string, ... ? @jacobdotcosta

**Comment by cmoulliard** [comment]
> * The default behavior is not to update components already updated

How can you achieve that ? Your sentence implies that know the versions of the components already updated in a previous job executed @jacobdotcosta

**Comment by cmoulliard** [comment]
> 1. coherent with the one

What is coherent ? Can you define the rule to verify/validate please @jacobdotcosta

**Comment by jacobdotcosta** [comment]
> > * If this option is set
> 
> How such an option is set ? Is it a boolean, a string, ... ? @jacobdotcosta

It's just a switch, no values associated.

**Comment by jacobdotcosta** [comment]
> > * The default behavior is not to update components already updated
> 
> How can you achieve that ? Your sentence implies that know the versions of the components already updated in a previous job executed @jacobdotcosta 

Whem a component is updated it should be marked in the release file as pointed in the process list.

```quote
7. Marks the component(s) as updated in the release file
if no changes are made the process should detect that and not push anything
```

**Comment by jacobdotcosta** [comment]
> > 1. coherent with the one
> 
> What is coherent ? Can you define the rule to verify/validate please @jacobdotcosta

Has the same value, I have rephrased it.

**Comment by cmoulliard** [comment]
Is it clear for you the description of this use case @metacosm @yharish991 @geoand @gytis @aureamunoz ? For me this is not clear enough

**Comment by jacobdotcosta** [comment]
I've just added an example. All this explanation might not replace a call/meet reviewing the information.

**Comment by yharish991** [comment]
> OPTIONAL switch to override overwriting components already updated
The default behavior is not to update components already updated. If this option/switch is set (no value needs to be associated) the process should override this behavior and force the update of all components.

I did not understand this, overwriting components in build-config.yml?

**Comment by yharish991** [comment]
> Identify the gitlab branch/MR which is being used

How do we identify the branch/MR? based on what criteria?

**Comment by jacobdotcosta** [comment]
> > Identify the gitlab branch/MR which is being used
> 
> How do we identify the branch/MR? based on what criteria?

The criteria is 2 lines below, 
```quote
the branch name must follow a predefined rule such as issues-manager-<major>.<minor>.<fix>
```

**Comment by jacobdotcosta** [comment]
> > OPTIONAL switch to override overwriting components already updated
> > The default behavior is not to update components already updated. If this option/switch is set (no value needs to be associated) the process should override this behavior and force the update of all components.
> 
> I did not understand this, overwriting components in build-config.yml?

The idea is that, once a component is updated with the information from JIRA, it won't be updated again. This is why we needed this switch, so that in a particular execution the components would be updated even though they were already marked as updated.

**Comment by yharish991** [comment]
> > > Identify the gitlab branch/MR which is being used
> > 
> > 
> > How do we identify the branch/MR? based on what criteria?
> 
> The criteria is 2 lines below,
> 
> ```
> the branch name must follow a predefined rule such as issues-manager-<major>.<minor>.<fix>
> ```

oh i see, look for the branch `issues-manager-<major>.<minor>.<fix>` initially, create it if it doesn't exist or use it if it already exists?

**Comment by yharish991** [comment]
> Marks the component(s) as updated in the release file

how is the component marked as updated? A new attribute be added to the component? something like below
?
```
- name: Dekorate
  jira:
    project: ENTSBT
    key: ENTSBT-968
    assignee: xxx
  properties:
  - dekorate
  updated: true
```

**Comment by jacobdotcosta** [comment]
> > Marks the component(s) as updated in the release file
> 
> how is the component marked as updated? A new attribute be added to the component?

Yes, a new attribute marking it as updated would be implemented.

**Comment by jacobdotcosta** [comment]
> > > > Identify the gitlab branch/MR which is being used
> > > 
> > > 
> > > How do we identify the branch/MR? based on what criteria?
> > 
> > 
> > The criteria is 2 lines below,
> > ```
> > the branch name must follow a predefined rule such as issues-manager-<major>.<minor>.<fix>
> > ```
> 
> oh i see, look for the branch `issues-manager-<major>.<minor>.<fix>` initially, create it if it doesn't exist or use it if it already exists?

yes, that's the idea.
